@startuml
skinparam backgroundColor grey
autonumber
actor User as user
participant "AuthServer" as srv
queue "Аудит" as audit
title <color:#FFE81F><size:25>Автонумерация: как это было?
user -> srv ++: Запрос **аутентификации по паролю**
srv -> srv: Обработка запроса
alt #moccasin passLoginEnabled = false
    srv --> user: Воспользуйтесь альтернативным\nспособом входа
    ...
else passLoginEnabled = true
    alt #orange Ошибка пароля
        srv -> audit: Событие входа
        srv --> user: Вход НЕ разрешен
        ...
    end
end
 srv -> audit: Событие входа
srv --> user--: Вход разрешен
user -> srv++: Повторный вход
note across: Повторяются шаги: 2 - 4
@enduml