@startuml
!include C:\Users\valik\IdeaProjects\PlantUML_SequenceLib\SequenceLib\src\SequenceLibIncludeFile_v4.puml
diagramInit(final,"Диаграмма для AnalystDays")

/'Как объявлять участников'/
BOX("Пример группировки участников в коробку", lightblue, "user,srv") /'В боксах'/
parties(srv2,"",,) /'Через parties, указал алиас из кастомных настроек'/
parties(database,"redis",redis,15) /'Через parties, полноценно, как это делается обычно'/

SEPARATOR(Первый вход)
rq(user,srv,++,"Запрос **аутентификации по паролю**","Комментарий для таблицы")
NOTE(,,azure,"Пример заметки на всю ширину диаграммы.\nМногострочность реализована только через \\n.")
audit(AUTH_LOGIN,,"Вход по паролю",srv) /'Автопостроение таблицы с событиями аудита. Если событие новое - не задано в настройках пользователя, будет также добавлено в список доработок'/
todo("Переименовать событие аудита") /'Автопостроение списка доработок'/
rq(srv,redis_srv,,"Обработка запроса","") /'Автоопределение типа участника и автообъявление его из rq/rs'/
rs(,,,"Обработка завершена","") /'Автоответ'/
NOTE(redis_srv,srv,azure,"Пример заметки поверх указанных участников")
anchor(st1) /'Якорь-ссылка, запоминает номер последней стрелки, после которой он вызван'/
ALT(moccasin,"passLoginEnabled = false")
    todo("Реализовать обработку параметра passLoginEnabled")
    config(passLoginEnabled, boolean) /'Автопостроение таблицы с параметрами и настройками. Если новые - не заданы в настройках пользователя, будет также добавлено в список доработок'/
    rs(srv,user,...,"Воспользуйтесь альтернативным\nспособом входа","Вход по паролю отключен")
    anchor(ans)
    audit(AUTH_LOGIN,FAILURE,"Вход по паролю отключен",srv)
ELSE(,"passLoginEnabled = true")
    OPT(orange,"Ошибка пароля")
        rs(*,ans,...,"Вход НЕ разрешен","Введен неверный пароль") /'Якоря можно использовать в rq/rs'/
        error(login_disabled) /'Автопостроение таблицы с ошибками. Если ошибка новая - не задана в настройках пользователя, будет также добавлено в список доработок'/
        audit(AUTH_LOGIN,FAILURE,"Введен неверный пароль",srv)
    END()
END()
rs(srv,user,--,"Вход разрешен","Пользователь попал в авторизованную зону")
audit(AUTH_LOGIN,SUCCESS,"Осуществлен вход по паролю",srv)
anchor(st2)
SEPARATOR(Повторный вход)

rq(,,++,"Повторный вход","Повторный вход возможен в пределах 15 минут")
NOTE(left,srv,azure,"Пример заметки слева от указанного участника")
REF(user,srv,,"Повторяются шаги: st1 - st2")
ORIGINAL()
@enduml