@startuml
/'Инклюдим файл библиотеки. Важно указать корректный путь на вашем компьютере'/
!include C:\Users\valik\IdeaProjects\PlantUML_SequenceLib\SequenceLib\src\SequenceLibIncludeFile_v5.puml

/'Инициируем работу с диаграммой с помощью библиотеки'/
diagramInit(final, Демонстрационная диаграмма) /''/

/'Объявляем участника из кастомной библиотеки {директория, где вы сохранили проект}\PlantUML_SequenceLib\SequenceLib\src\customerEnviroment\customAliasMap.puml'/
parties(user,"",,)

/'Объединяем участников в бокс, применяем множественное перечисление'/
BOX("сервис",lightblue,"srv,core")

/'Метка на диаграмме'/
SEPARATOR(Начало)

/'Активация линии жизни участника srv'/
ACTIVATE(srv)

/'Отрисовка стрелки'/
rq(user,srv,,"Тест","")

/'Начинаем аудит события'/
audit(new_audit_event,,"",srv)

/'Нерешенная и решенная зависимости'/
dependFrom("srv", "Не реализовал новый АПИ", "Требование", "Номер задачи", "Комментарий", "Админ","")
dependFrom("srv", "Не реализовал новый АПИ", "Требование", "Номер задачи", "Комментарий", "Админ","Реализовал")

/'Альтернатива с затемненным оранжевым фоном'/
ALT(DARKEN(orange,15),"Альтернативный ответ")
    /'Автоответ'/
    rs(,,,"","")

    /'Фиксируем новую ошибку'/
    error(new_demo_error)

    /'Фиксируем задачу в списке'/
    todo("20.02.2026: Новая ошибка new_demo_error")

    /'Обратите внимание, в списке доработок будет два сообщения, из процедуры error и из todo'/

    /'Завершаем аудит события с ошибкой'/
    audit(new_audit_event,FAILURE,"Текст события",srv)
END()

/'Автоответ с копирование по номеру'/
rs(*,2,--,"","")

/'Завершаем аудит события успешно'/
audit(new_audit_event,,"",srv)
/'Проксирующий вызов'/
rq(user,"srv,core",++,"Проксирующий вызов","")

/'Якорь, копирует идентификатор последней отрисованной стрелки'/
anchor(anc1)

/'Копирование стрелки по якорю'/
rq(*,anc1,++#tan,"Копирование через якорь","")
config(new_feature_enabled, boolean)

/'Выведем код этой диаграммы в оригинальном синтаксисе'/
ORIGINAL()
/'Если появилась заметка с текстом про режим final, перейдите в 6 строку и замените "draf" на "final"'/
@enduml