                                                                                          Диаграмма: <color:blue>Диаграмма для AnalystDays
                                                                                           Режим: <color:blue>final</color>; Генерация кода в оригинальном синтаксисе: <color:blue>**включена**

                                                                                                                        ┌─┐
                                                                                                                        ║"│
                                                                                                                        └┬┘
                                                                                                                        ┌┼┐
                                                                                                                         │                                ┌──────────┐
                                                                                                                        ┌┴┐                               │AuthServer│
                                                                                                                   Пользователь                           └─────┬────┘
                                                                                                                         │                                      │
                                                                                                                         │           ╔═════════════╗            │
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═══════════╣ Первый вход ╠════════════╪═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                                                                                         │           ╚═════════════╝            │
                                                                                                                         │                                      │
                                                                                                                         𝟏 Запрос **аутентификации по паролю** ┌┴┐
                                                                                                                         │───────────────────────────────────> │ │
                                                                                                                         │                                     │ │
                                                                                                                         │             ┌──────────────────────────────────────────────────┐
                                                                                                                         │             │<color:red><&media-play> <color:black>AUTH_LOGIN  │
                                                                                                                         │             └──────────────────────────────────────────────────┘
                                                                                                                         │                                     │ │ ─ ─ ┐
                                                                                                                         │                                     │ │     | 𝟐 Обработка запроса
                                                                                                                         │                                     │ │ < ─ ┘
                                                                                                                         │                                     │ │
                                                                                                                         │                                     │ │
                                                                                              ╔══════╤═══════════════════╪═════════════════════════════════════╪═╪════════════════════════════════════════╗
                                                                                              ║ ALT  │  passLoginEnabled = false                               │ │                                        ║
                                                                                              ╟──────┘                   │                                     │ │                                        ║
                                                                                              ║                          │  𝟑 Воспользуйтесь альтернативным    │ │                                        ║
                                                                                              ║                          │  способом входа                     │ │                                        ║
                                                                                              ║                          │<─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ │ │                                        ║
                                                                                              ║                          │                                     └┬┘                                        ║
                                                                                              ║                          │                                      │                                         ║
                                                                                              ║                          │                                      │                                         ║
                                                                                              ║                          │                                      │                                         ║
                                                                                              ║                          │                                      │                                         ║
                                                                                              ║                          .             ┌──────────────────────────────────────────────────┐               ║
                                                                                              ║                          .             │<color:red><&media-stop> <color:black>AUTH_LOGIN  │               ║
                                                                                              ╠═══════════════════════════════════════════════════════════════════════════════════════════════════════════╣
                                                                                              ║ [passLoginEnabled = true].                                     │ │                                        ║
                                                                                              ║                          │                                     │ │                                        ║
                                                                                              ║         ╔══════╤═════════╪═════════════════════════════════════╪═╪══════════════════════════════╗         ║
                                                                                              ║         ║ ALT  │  Ошибка пароля                                │ │                              ║         ║
                                                                                              ║         ╟──────┘         │                                     │ │                              ║         ║
                                                                                              ║         ║                │        𝟒 Вход НЕ разрешен           │ │                              ║         ║
                                                                                              ║         ║                │<─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ │ │                              ║         ║
                                                                                              ║         ║                │                                     └┬┘                              ║         ║
                                                                                              ║         ║                │                                      │                               ║         ║
                                                                                              ║         ║                │                                      │                               ║         ║
                                                                                              ║         ║                │                                      │                               ║         ║
                                                                                              ║         ║                │                                      │                               ║         ║
                                                                                              ║         ║                .             ┌──────────────────────────────────────────────────┐     ║         ║
                                                                                              ║         ║                .             │<color:red><&media-stop> <color:black>AUTH_LOGIN  │     ║         ║
                                                                                              ║         ╚══════════════════════════════└──────────────────────────────────────────────────┘═════╝         ║
                                                                                              ╚════════════════════════════════════════════════════════════════╪═╪════════════════════════════════════════╝
                                                                                                                         │                                     └┬┘
                                                                                                                         │           𝟓 Вход разрешен            │
                                                                                                                         │<─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─│
                                                                                                                         │                                      │
                                                                                                                         │             ┌──────────────────────────────────────────────────┐
                                                                                                                         │             │<color:red><&media-stop> <color:black>AUTH_LOGIN  │
                                                                                                                         │             └──────────────────────────────────────────────────┘
                                                                                                                         │                                      │
                                                                                                                         │          ╔════════════════╗          │
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════╣ Повторный вход ╠══════════╪═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                                                                                         │          ╚════════════════╝          │
                                                                                                                         │                                      │
                                                                                                                         │         𝟔 Повторный вход            ┌┴┐
                                                                                                                         │───────────────────────────────────> │ │
                                                                                                                         │                                     │ │
                                                                                                                  ╔══════╧═════════════════════════════════════╧═╧══════╗
                                                                                                                  ║Повторяются шаги: 2 - 5                             ░║
                                                                                                                  ╚══════╤═════════════════════════════════════╤═╤══════╝
  ╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╧═════════════════════════════════════╧═╧══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
  ║**ОПИСАНИЕ ПРОЦЕДУР БИБЛИОТЕКИ**                                                                                                                                                                                                                                                    ░║
  ║====                                                                                                                                                                                                                                                                                 ║
  ║| Наименование | Описание | Исходный синтаксис | Пример | Переменные |                                                                                                                                                                                                               ║
  ║| rq | Рисует сплошную стрелку\n от участника-инициатора\n к участнику-исполнителю | -> | rq(initiator,executor,liveline,action,comment) | initiator - инициатор,executor\n - исполнитель,liveline\n - линия жизни,action\n - текст над стрелкой,comment\n - текст комментария |     ║
  ║| rs | Рисует пунктирную стрелку\n от участника-инициатора\n к участнику-исполнителю | --> | rs(initiator,executor,liveline,action,comment) | initiator - инициатор,executor\n - исполнитель,liveline\n - линия жизни,action\n - текст над стрелкой,comment\n - текст комментария |  ║
  ║| parties | Рисует участников диаграммы | participant имя as алиас order | parties(type,name,as,order) | type - тип участника,name\n - имя участника,as -\n вспомогательная переменная,order\n - порядок расположения |                                                              ║
  ║| audit | Рисует нотификацию об\n отправке события в аудит | - | audit(event,status,desc,participant) | event - имя события,status\n - статус, может быть\n пустым,desc - описание\n для таблицы,participant\n - линия участника, на\n которой будет отображена\n нотификация |      ║
  ║| anc | Якорь, запоминает текущее\n значение autonumber | - | anchor(name) | name - имя якоря |                                                                                                                                                                                      ║
  ║| BOX | Рисует объединение участников\n в бокс | box nameBox color | BOX(name,color, участник1|участник2) | name - наименование бокса,color\n - цвет бокса, список\n участников через запятую |                                                                                      ║
  ║| ALT | Рисует выделение альтернативного\n сценария | alt color case | ALT(color,description | color - цвет кейса,description\n - описание кейса |                                                                                                                                   ║
  ║| OPT | Рисует выделение опционального\n сценария | opt color case | OPT(color,description | color - цвет кейса,description\n - описание кейса |                                                                                                                                     ║
  ║| PAR | Рисует выделение параллельного\n сценария | par color case | PAR(color,description | color - цвет кейса,description\n - описание кейса |                                                                                                                                     ║
  ║| GROUP | Рисует выделение сгруппированного\n сценария | group color case | GROUP(color,description | color - цвет кейса,description\n - описание кейса |                                                                                                                            ║
  ║| LOOP | Рисует выделение цикличного\n сценария | loop color case | LOOP(color,description | color - цвет кейса,description\n - описание кейса |                                                                                                                                     ║
  ║| ELSE | Рисует выделение альтернативного\n сценария | elst color case | ELSE(color,description | color - цвет кейса,description\n - описание кейса |                                                                                                                                ║
  ║| END | Закрывает альты, опты\n и тд | end | END() | - |                                                                                                                                                                                                                             ║
  ║| NOTE | Рисует заметку в заданном\n месте | note across: или note over participant: | NOTE(position1,position2,color,description) | position1,position2 -\n управляют положением\n заметки,color - цвет\n фона заметки,description\n - содержание, текст заметки |                  ║
  ║| REF | Рисует ссылку в заданном\n месте | ref across: или ref over participant: | REF(position1,position2,color,description) | position1,position2 -\n управляют положением\n ссылки, color - цвет\n фона ссылки, description\n - содержание, текст ссылки |                        ║
  ║| ACTIVATE | Рисует линию жизни участника | activate participantname | ACTIVATE(party) | party - алиас участника |                                                                                                                                                                   ║
  ║| DEACTIVATE | Завершает линию жизни\n участника | deactivate participantname | DEACTIVATE(party) | party - алиас участника |                                                                                                                                                        ║
  ║| diagramInit | Инициирует диаграмма,\n рисует заголовок с параметрами |  | diagramInit(draft,name) | mode - режим работы для\n постановок (draft, final),\n name - заголовок диаграммы |                                                                                            ║
  ║| LEGEND | Рисует легенду диаграммы\n в зависимости от режима\n работы | - | LEGEND() | - |                                                                                                                                                                                          ║
  ║| ORIGINAL | Генерирует заметку с исходным синтаксисом | - | ORIGINAL() | - |                                                                                                                                                                                                        ║
  ║| HELP | Генерирует заметку с описанием процедур | - | HELP(procName) | procName - имя процедуры,\n если пустое показывает\n все |                                                                                                                                                   ║
  ╚══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╤═════════════════════════════════════╤═╤══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
                                                                              ╔══════════════════════════════════════════╧═════════════════════════════════════╧═╧═════════════════════════════════════════╗
                                                                              ║@startuml                                                                                                                  ░║
                                                                              ║                                                                                                                            ║
                                                                              ║autonumber                                                                                                                  ║
                                                                              ║skinparam dpi 100                                                                                                           ║
                                                                              ║skinparam maxMessageSize 200                                                                                                ║
                                                                              ║skinparam backgroundColor LightGray                                                                                         ║
                                                                              ║skinparam sequence {                                                                                                        ║
                                                                              ║ArrowColor blue                                                                                                             ║
                                                                              ║ActorBorderColor blue                                                                                                       ║
                                                                              ║LifeLineBorderColor blue                                                                                                    ║
                                                                              ║LifeLineBackgroundColor #White                                                                                              ║
                                                                              ║ParticipantBorderColor blue                                                                                                 ║
                                                                              ║ParticipantBackgroundColor DodgerBlue                                                                                       ║
                                                                              ║ParticipantFontName Impact                                                                                                  ║
                                                                              ║ParticipantFontSize 17                                                                                                      ║
                                                                              ║ParticipantFontColor #A9DCDF                                                                                                ║
                                                                              ║ActorBackgroundColor DodgerBlue                                                                                             ║
                                                                              ║ActorFontColor DeepSkyBlue                                                                                                  ║
                                                                              ║ActorFontSize 17                                                                                                            ║
                                                                              ║ActorFontName Aapex                                                                                                         ║
                                                                              ║}                                                                                                                           ║
                                                                              ║                                                                                                                            ║
                                                                              ║title Диаграмма: <color:blue>Диаграмма для AnalystDays                                                                      ║
                                                                              ║header <color:black>by SequenceLib.v.4.0.\n <color:black>Author: PVR                                                        ║
                                                                              ║                                                                                                                            ║
                                                                              ║participant "AuthServer" as srv order 1                                                                                     ║
                                                                              ║actor "Пользователь" as user                                                                                                ║
                                                                              ║                                                                                                                            ║
                                                                              ║                                                                                                                            ║
                                                                              ║== Первый вход ==                                                                                                           ║
                                                                              ║user -> srv ++: Запрос **аутентификации по паролю**                                                                         ║
                                                                              ║        hnote over srv #lightyellow/lightgreen: <color:red><&media-play> <color:black>AUTH_LOGIN                            ║
                                                                              ║srv --> srv : Обработка запроса                                                                                             ║
                                                                              ║alt #moccasin passLoginEnabled = false                                                                                      ║
                                                                              ║    srv --> user : Воспользуйтесь альтернативным\nспособом входа                                                            ║
                                                                              ║    ...                                                                                                                     ║
                                                                              ║        hnote over srv #orange/red: <color:red><&media-stop> <color:black>AUTH_LOGIN                                        ║
                                                                              ║else  passLoginEnabled = true                                                                                               ║
                                                                              ║alt #orange Ошибка пароля                                                                                                   ║
                                                                              ║    srv --> user : Вход НЕ разрешен                                                                                         ║
                                                                              ║    ...                                                                                                                     ║
                                                                              ║        hnote over srv #orange/red: <color:red><&media-stop> <color:black>AUTH_LOGIN                                        ║
                                                                              ║end                                                                                                                         ║
                                                                              ║                                                                                                                            ║
                                                                              ║end                                                                                                                         ║
                                                                              ║                                                                                                                            ║
                                                                              ║srv --> user --: Вход разрешен                                                                                              ║
                                                                              ║        hnote over srv #lightyellow/lightgreen: <color:red><&media-stop> <color:black>AUTH_LOGIN                            ║
                                                                              ║                                                                                                                            ║
                                                                              ║                                                                                                                            ║
                                                                              ║== Повторный вход ==                                                                                                        ║
                                                                              ║user -> srv ++: Повторный вход                                                                                              ║
                                                                              ║note across : Повторяются шаги: 2 - 5                                                                                       ║
                                                                              ║                                                                                                                            ║
                                                                              ║legend                                                                                                                      ║
                                                                              ║Карта процесса (полная)                                                                                                     ║
                                                                              ║====                                                                                                                        ║
                                                                              ║| Код | ИC-инициатор | ИС-исполнитель | Тип взаимодействия | Тип сценария | Метод API | Описание |                          ║
                                                                              ║|---|---|---|---|---|---|---|                                                                                               ║
                                                                              ║| 1 | Пользователь | AuthServer | rq | default | Запрос **аутентификации по паролю** | Комментарий для таблицы |            ║
                                                                              ║| 2 | AuthServer | AuthServer | rs | default | Обработка запроса |  |                                                       ║
                                                                              ║| 3 | AuthServer | Пользователь | rs | alt | Воспользуйтесь альтернативным\nспособом входа | Вход по паролю отключен |      ║
                                                                              ║| 4 | AuthServer | Пользователь | rs | alt | Вход НЕ разрешен | Введен неверный пароль |                                    ║
                                                                              ║| 5 | AuthServer | Пользователь | rs | default | Вход разрешен | Пользователь попал в авторизованную зону |                 ║
                                                                              ║| 6 | Пользователь | AuthServer | rq | default | Повторный вход | Повторный вход возможен в пределах 15 минут |             ║
                                                                              ║                                                                                                                            ║
                                                                              ║Список доработок                                                                                                            ║
                                                                              ║====                                                                                                                        ║
                                                                              ║| № | id обнаружения | Суть доработки|                                                                                      ║
                                                                              ║|---|---|---|                                                                                                               ║
                                                                              ║| 1 | 1 | Необходимо реализовать новое событие аудита AUTH_LOGIN. Отправитель: AuthServer |                                 ║
                                                                              ║| 2 | 1 | Переименовать событие аудита |                                                                                    ║
                                                                              ║| 3 | 2 | Реализовать обработку параметра passLoginEnabled |                                                                ║
                                                                              ║| 4 | 2 | Необходимо добавить новый параметр: passLoginEnabled. Тип: boolean |                                              ║
                                                                              ║                                                                                                                            ║
                                                                              ║Новые события аудита                                                                                                        ║
                                                                              ║====                                                                                                                        ║
                                                                              ║| # | Код события | Статус | Объект | Тип события | Операция | Краткое описание | Подробное описание | Доп.параметры |      ║
                                                                              ║|---|---|---|---|---|---|---|---|---|                                                                                       ║
                                                                              ║| 1 | AUTH_LOGIN | SUCCESS \n FAILURE |  |  |  |  |  | Вход по паролю |                                                     ║
                                                                              ║                                                                                                                            ║
                                                                              ║Новые параметры                                                                                                             ║
                                                                              ║====                                                                                                                        ║
                                                                              ║| # | Наименование | Тип1 | Тип2 | Значение | Описание |                                                                    ║
                                                                              ║|---|---|---|---|---|---|                                                                                                   ║
                                                                              ║| 1 | passLoginEnabled | параметр configMap \n coreSetting | boolean |  |  |                                                ║
                                                                              ║                                                                                                                            ║
                                                                              ║end legend                                                                                                                  ║
                                                                              ║@enduml                                                                                                                     ║
                                                                              ╚════════════════════════════════════════════════════════════════════════════════╤═╤═════════════════════════════════════════╝
                                                                                                                        ┌─┐                               │Auth│ │ver│
                                                                                                                        ║"│                               └────│ │───┘
                                                                                                                        └┬┘                                    │ │
                                                                                                                        ┌┼┐                                    │ │
                                                                                                                         │                                     │ │
                                                                                                                        ┌┴┐                                    │ │
                                                                                                                                                               └┬┘
