@startuml
title "AliasController"

!$print = "<color:red><size:15><&print></color>"
!unquoted function tag($symbol)
    !return "<color:red><size:15><&"+ $symbol + "></color>"
!end function

legend top left
Легенда диаграммы
====
1. ввести в редакторе "имя процедуры/ функции" - вызвать в редакторе плагина plantUml пользовтельскуй процедуру/функцию - интерфейс
2. Вызвать "действие/ имя процедуры функции" - вызов процедуры/функции внутри другой процедуры функции
3. repeat - обозначение цикла foreach
4. Действие (например найти/сформировать) - обозначение простой функции/процедуры
5. Сложные процедуры/функции - состоят из проверок, циклов и вызовов простых процедур/функций, объединены в пакеты
6. Примеры объединены в группы, в названии которых указано - это примеры
end legend

start
:Ввести parties;
group Примеры ввода #moccasin
    split
    :parties(user);
    split again
    :parties("user,kafka");
    split again
    :parties("participant", "Имя участника", алиас, порядок);
    end split
end group

package parties #tan
    :Вызвать partyInputController;
end group
package partyInputController #tan
    :Создать пустой массив $aliasArrayToCheck;
    :Проверить заполненные поля: тип, имя, алиас, порядок;
    if (Заполнен только тип,\nт.е. передан массив, и\nостальные поля пустые?) then (Нет)
        :Установить alias == stringToArray(alias);
    else (Да)
        :Установить alias == stringToArray(type);
        :Установить type == "";
    endif
    repeat:ЦИКЛ foreach item in alias\n(stringToArray)
        :Создать объект $aliasToCheck,
        {"alias": {
            "type":"value",
            "name":"value",
            "order":"value"}};
        :Добавить объект $aliasToCheck
        в массив $aliasArrayToCheck;
    repeat while (Весь массив обработан?) is (Нет) not (Да)
    :Вызвать checkAliasInCurrentAliasMap(aliasArrayToCheck);
    end group
    package checkAliasInCurrentAliasMap #tan
        repeat:ЦИКЛ foreach item in $aliasArrayToCheck
        :tag(print) Вызвать findAlias(findInCurrentAliasMap == 1)
        Найти алиас в $currentAliasMap;
        note right: findInCurrentAliasMap == 1 - искать алиас в текущей диаграмме,\n0 - искать в кастомных настройках
        if(Найден?) then(Да)
        else(Нет)
           :Определить findInCustomAliasMap == 0;
            :Вызвать findAlias(findInCurrentAliasMap == 0):
            Найти алиас в $customAliasMap;
            if(Найден?) then(Нет)
                :вызвать тудушку: добавьте интеграцию с алисаом;
            else(Да)
                :Определить findInCustomAliasMap == 1;
            endif
            :tag(cog) Вызвать процедуру getPartyAttributeByAlias(alias, findInCustomAliasMap, attrType=name, attrValue==$aliasArrayToCheck.alias.name);
            group "getPartyAttributeByAlias" #moccasin
                if(findInCustomAliasMap == 0?) then(Да)
                    :Вызвать функцию getPartyDataByAlias(attrType),
                     обновить name для текущего объекта;
                else(Нет)
                    if(attrValue пустое?) then(Да)
                        :Достать attrValue из $customAliasMap,
                        обновить его в attrType для текущего объекта;
                    else(Нет)
                        if(attrValue совпадает\nс attrValue такого же attrType\nдля текущего alias из $customAliasMap) then(Нет)
                            :Вызвать тудушку: В текущей диаграмме используется alias,
                            уже присутствующий в $customAliasMap с другим именем.
                            Измените его перед добавлением в $customAliasMap.;
                        else(Да)
                        endif
                    endif
                endif
            end group
            :tag(cog) Вызвать процедуру getPartyAttributeByAlias(alias, findInCustomAliasMap, attrType=type, attrValue==$aliasArrayToCheck.alias.type);
            group "getPartyAttributeByAlias" #moccasin
                if(findInCustomAliasMap == 0?) then(Да)
                    :Вызвать функцию getPartyDataByAlias(attrType),
                     обновить name для текущего объекта;
                else(Нет)
                    if(attrValue пустое?) then(Да)
                        :Достать attrValue из $customAliasMap,
                        обновить его в attrType для текущего объекта;
                    else(Нет)
                        if(attrValue совпадает\nс attrValue такого же attrType\nдля текущего alias из $customAliasMap) then(Нет)
                            :Вызвать тудушку: В текущей диаграмме используется alias,
                            уже присутствующий в $customAliasMap с другим именем.
                            Измените его перед добавлением в $customAliasMap.;
                        else(Да)
                        endif
                    endif
                endif
            end group
            :Добавить нового участника в $currentAliasMap;
        endif

    repeat while (Весь массив обработан?) is (Нет) not (Да)
    :Вызвать partiesOutputController
    для обновленного $aliasArrayToCheck;
    end group


@enduml
