@startuml
title "AliasController"
legend top left
Легенда диаграммы
====
1. ввести в редакторе "имя процедуры/ функции" - вызвать в редакторе плагина plantUml пользовтельскуй процедуру/функцию - интерфейс
2. Вызвать "действие/ имя процедуры функции" - вызов процедуры/функции внутри другой процедуры функции
3. repeat - обозначение цикла foreach
4. Действие (например найти/сформировать) - обозначение простой функции/процедуры
5. Сложные процедуры/функции - состоят из проверок, циклов и вызовов простых процедур/функций, объединены в пакеты
6. Примеры объединены в группы, в названии которых указано - это примеры
end legend

start
:Ввести parties;
group Примеры ввода #moccasin
    split
    :parties(user);
    split again
    :parties("user,kafka");
    split again
    :parties("participant", "Имя участника", алиас, порядок);
    end split
end group
package parties #tan
    :Вызвать checkPartyInput(type, name, alias, order);
end group
package checkPartyInput #tan
    :Проверить заполненные поля: тип, имя, алиас, порядок;
    if (Заполнен только тип, и\nостальные поля пустые?) then (Нет)
        :Установить alias == stringToArray(alias);
    else (Да)
        :Преобразоватья type в строку == %string(type);
        :Установить alias == stringToArray(type);
        :Установить type == "";
    endif
    :Вызвать aliasArrayToCheckBuilder(type, name, alias, order);
end group

package aliasArrayToCheckBuilder #tan
    :Создать пустой массив $aliasArrayToCheck;
    repeat:ЦИКЛ foreach item in alias\n(stringToArray);
        :Создать объект $aliasToCheck,
        {"alias": {
            "type":"value",
            "name":"value",
            "order":"value"}};
        :Добавить объект $aliasToCheck
        в массив $aliasArrayToCheck;
    repeat while (Весь массив обработан?) is (Нет) not (Да)
    :Вызвать checkAliasAttributes($aliasArrayToCheck);
end group

package checkAliasAttributes #tan
    repeat:ЦИКЛ foreach item in $aliasArrayToCheck
    :Вызвать findAlias(alias);
    package findAlias #moccasin
        :Найти алиас в $currentAliasMap;
        if(Найден?) then(Да)
           :Вызвать Нотификашку: вы попытались
           добавить участника с алиасом "alias",
           уже существующим в диаграмме.
           Проверьте корректность алиаса.;
        else(Нет)
        :Найти алиас в $customAliasMap;
            if(Найден?) then(Нет)
                :вызвать тудушку:
                добавьте интеграцию с алисом;
            else(Да)
                :Создать глобальный список
                $aliasAttributesToCheck = [name,type];
                repeat:ЦИКЛ foreach item in $aliasAttributesToCheck;
                package aliasNameToCheck #azure
                    if(alias.item == NULL) then(Да)
                        :Обновить aliasArrayToCheck:
                        alias.item = custom.alias.item;
                    else(Нет)
                        if(alias.item == custom.alias.item ?) then(Нет)
                            :Вызвать тудушку:
                            item участника с алиасом alias отличается
                            от идентичного в пользовательских настройках -
                            проверьте актуальность пользовательских настроек;
                        else(Да)
                        endif
                    endif
                end group
                repeat while (Все атрибуты проверили?) is (Нет) not (Да)
            endif
        endif
    end group
    :Увеличить $orderId на 1;
    :Записать $orderId в $aliasArrayToCheck;
    :Добавить нового участника в $currentAliasMap;
    repeat while (Весь массив обработан?) is (Нет) not (Да)
    :Вызвать partyOutputController($aliasArrayToCheck);
end group

package partyOutputController #tan
    repeat:ЦИКЛ foreach item in $aliasArrayToCheck;
:вывод $aliasArrayToCheck.item.type $aliasArrayToCheck.item.name $aliasArrayToCheck.item.alias $aliasArrayToCheck.item.order; 
    repeat while (Весь массив обработан?) is (Нет) not (Да)
end group
stop
@enduml
