@startuml
!$testJson = {
    "a": {
        "name": "A",
        "type": "letter"
        },
    "b": {
        "name": "B",
        "type": "letter"
        }
    }

!$jsonForSearch = {
    "a": {
      "name": "A",
      "type": "letterк"
      },
    "b": {
      "name": "sdf",
      "type": "letter"
      },
    "c": {
      "name": "C",
      "type": "letter"
      }
    }

!$defTypesToCheck = ["name", "type"]

!unquoted procedure testSearch()
    !foreach $item in $testJson
        !if %json_key_exists($jsonForSearch, $item)
            !foreach $attr in $defTypesToCheck
                !if $testJson[$item][$attr] != $jsonForSearch[$item][$attr]
                    note across: Выявлено несоответствие для объекта $item:\nзначение $attr <color: red>$testJson[$item][$attr]</color> не совпадает\nс <color: red>$jsonForSearch[$item][$attr]</color> из пользовательских настроек
                !endif
            !endfor
        !endif
    !endfor
!endprocedure

a -> b: adsf
testSearch()
@enduml