@startuml
/'
В этом тесте решается задача:
есть два json: провреяемый и эталонный. объекты провреяемого ищутся в эталонном, при вхождении сравниваются значения.
Ошибки из-за препроцессора: он проверяет все варианты, и когда объект провреяемого не входит в эталонн
'/


!$testJson = {
    "a": {
        "name": "A",
        "type": "letter"
        },
    "c": {
        "name": "B",
        "type": "letter"
        }
    }

!$jsonForSearch = {
    "a": {
      "name": "",
      "type": "letterц"
      },
    "c": {
      "name": "C",
      "type": "letter"
      }
    }

!$defTypesToCheck = ["name", "type"]

!unquoted procedure testSearch()
    !foreach $item in %get_json_keys($testJson)
        !if %json_key_exists($jsonForSearch, $item)
            !foreach $attr in $defTypesToCheck
                !if $testJson[$item][$attr] != $jsonForSearch[$item][$attr]
                    note across: Выявлено несоответствие для объекта $item:\nзначение $attr <color: red>$testJson[$item][$attr]</color> не совпадает\nс <color: red>$jsonForSearch[$item][$attr]</color> из пользовательских настроек
                !endif
            !endfor
        !endif
    !endfor
!endprocedure

a -> b: adsf
testSearch()
@enduml