@startuml
/'Вспомогательная процедура отрисовки участников: формирует мапу имя:алиас'/
!unquoted procedure parties($partyType, $name="", $alias="", $order="")
%invoke_procedure("partiesController", $partyType, $name, $alias, $order)
!endprocedure

/'Логика контроллера
1. Проверять существование участника с переданным в пользовательских настройках. Если не существует:
   проверять на дефолтный тип участника,
   добавлять его в пользовательские настройки для будущих проверок в диаграмме
   вызывать тудушку с текстом - добавить новую интеграцию, а также обновить библиотеку интеграций {alias:{type,name,order}}
'/


/'Получить имя по алиасу'/
!unquoted function getNameByAlias($aliasToFind)
    !return $customAliasMap[$aliasToFind].name
!end function

/'Проверка наличия участника в пользовательской библиотеке'/
!unquoted function checkAliasInCustomEnvironments($aliasToCheck)
    !$result = 0
    !if %json_key_exists($customAliasMap, $aliasToCheck)
        !$result = 1
    !endif
    !return $result
!end function

/'Проверка наличия участника в текущей диаграмме библиотеке'/
!unquoted function checkAliasInCurrentDiagram($aliasToCheck)
    !$result = 0
    !if %json_key_exists($currentAliasMap, $aliasToCheck)
        !$result = 1
    !endif
    !return $result
!end function


/'Проверка уникальности участника с переданным алиасом'/
!unquoted procedure checkUniqueAliasNameInCustomEnvironments($aliasToFind, $name)
    !if checkAliasInCustomEnvironments($aliasToFind) == 1
        !if $customAliasMap[$aliasToFind].name != $name
        !assert В пользовательской библиотеке $customAliasMap уже существует участник с таким алиасом и другим именем.
        !endif
    !endif
!end procedure



'/