@startuml
!$customAliasMap = {
    "user" : {
      "type": "actor",
      "name": "Пользователь"
    },
    "srv" : {
      "type": "participant",
      "name": "Ваш сервис",
      "order": "0"
    }
}