@startuml
title "AliasController Logic"
split
-[hidden]->
:вызвать parties;
split again
-[hidden]->
:вызвать BOX;
split again
-[hidden]->
:вызвать rq/ rs;
split again
-[hidden]->
:вызвать ACTIVATE/ DEACTIVATE;
end split
repeat
:проверить параметры нового участника;
if(передан один алиас?) then(Нет)
    :запустить цикл для каждого алиаса из группы;
else(Да)
endif
repeat while (Остались участники?) is (Да)
if(Имя указано?) then(Нет)
    :вычислить новое имя на основании алиаса:
    * сделать первую букву заглавной;
else(Да)
endif
:проверить алиас в диаграмме;
if(Найден?) then(Нет)
    :проверить алиас в кастомной либе;
    if(Найден?) then(Нет)
        :вызвать тудушку: добавьте интеграцию с алисаом;
    else(Да)
        :сравнить имя нового участника с именем из либы;
        if(Совпадает?) then(Нет)
            :Вызвать тудушку: Данный участник найден в кастомной либе, возможно вы ошиблись?
            Если данные верны, чтобы добавить его в кастомную либу, нужно указать уникальный алиас;
        else(Да)
        endif
    endif
else(Да)
endif
:добавить объект с этим алиасом в диаграмму;
:вызвать билдер для отрисовки участника в диаграме;
stop

@enduml
