@startuml
/'Мапа алиасов'/
!$partyTypes = {
    "user": "actor",
    "client": "actor",
    "redis": "database",
    "PostgreSql": "database",
    "postgre": "database",
    "postgres": "database",
    "postgreSQL": "database",
    "kafka": "queue",
    "queue": "queue",
    "rabbit": "queue",
    "rabbitMQ": "queue",
    "MQ": "queue"
   }

!$defaultTypes = [
    "participant",
    "actor",
    "queue",
    "boundary",
    "control",
    "entity",
    "database",
    "collections"
]