@startuml
title "AliasController"

:вызвать parties;
split
:parties(user);
split again
:parties("user,kafka");
split again
:parties("participant", "Имя участника", алиас, порядок);
end split
while (Заполнен только тип и все остальные поля пустые?) is (Да)
    :Сформировать список объектов
     на основании строки из типа;
    repeat: Запустить aliasCheck для каждого alias из списка;
        :Найти алиас в $currentAliasMap;
        if(Найден?) then(Нет)
            :Найти алиас в $customAliasMap;
            if(Найден?) then(Нет)
                :вызвать тудушку: добавьте интеграцию с алисаом;
                :Сформировать имя на основании алиаса;
                :Определить тип на основании алиаса;
            else(Да)
                :Достать имя из $customAliasMap;
                :Достать тип из $customAliasMap;
            endif
        else(Да)
        endif
    repeat while (Есть еще объекты в списке?) is (Да) not (Нет)

endwhile (Нет)
:добавить объект с этим алиасом в $currentAliasMap;
:вызвать билдер для отрисовки участника в диаграме;

stop

@enduml
