@startuml
/'TODO Нужна процедура для стратегии вывода текста в оригинальном синтаксисе планта по стратегии в json'/

a->b: "Hello world"

!$objTemplate = {
    "parties": {
        "operation" : "parties",
        "testPartyVariables": ["type", "name", "alias", "order"],
        "testPartyRaw": {
            "type" : "",
            "name" : "",
            "as" : "as",
            "alias" : "",
            "order" : ""
        }
    }
}

!unquoted procedure printParties($type, $name, $alias, $order="")
    %invoke_procedure("outputBuilder", parties, $type, $name, $alias, $order)
!endprocedure

!unquoted procedure outputBuilder($list0, $list1, $list2="", $list3="", $list4="", $list5="", $list6="", $list7="", $list8="", $list9="", $list10="")
    !$listOut = %call_user_func("addVariablesToArray", $list1, $list2, $list3, $list4, $list5, $list6, $list7, $list8, $list9, $list10)
    !$listTemplate = $objTemplate[$list0].testPartyVariables
    !$out = %call_user_func("createJsonObject", $listTemplate, $listOut)

    note across: outputBuilder\n$list0\n$listTemplate\n$listOut\n$out\n%get_json_keys($out)
    !$i = 0
    !foreach $item in %get_json_keys($objTemplate[$list0].testPartyRaw)
        note across:  $item]
/'
        !$i = $i + 1
        !$outVar = "outVar" + $i
        !if %json_key_exists($out, $item)
            !$outVar = %set_variable_value($outVar, $out.item)
        !else
            !$outVar = %set_variable_value($outVar, $objTemplate[$list0].testPartyRaw.item)
        !endif
'/
    !endfor
    note across: %get_variable_value(outVar1), cve(outVar2), cve(outVar3), cve(outVar4), cve(outVar5), cve(outVar6), cve(outVar7), cve(outVar8), cve(outVar9), cve(outVar10)
'    %invoke_procedure("printRaw", cve(outVar1), cve(outVar2), cve(outVar3), cve(outVar4), cve(outVar5), cve(outVar6), cve(outVar7), cve(outVar8), cve(outVar9), cve(outVar10))
!endprocedure

!unquoted function getVar($var)
    !if
    !endif
    !return
!end function


!unquoted function createJsonObject($names, $values)
    /'Явно ограничиваем $names - это всегда массив из шаблонов '/
    /'Явно ограничиваем names - это всегда массив из переменных '/
    !$names = %str2json($names)
    !$values = %str2json($values)
    !$i = 0
    !$tempObject = {}
    !foreach $item in $values /'В объект добавляем только значения из массива $values'/
        !$tempObject = %json_add($tempObject, $names[$i], $values[$i])
        !$i = $i + 1
    !endfor
    !return $tempObject
!end function


!unquoted function addVariablesToArray($var1, $var2, $var3, $var4, $var5, $var6, $var7, $var8, $var9, $var10)
    !$list = []
    !if $var1 != ""
    !$list = %json_add($list, $var1)
    !endif
    !if $var2 != ""
    !$list = %json_add($list, $var2)
    !endif
    !if $var3 != ""
    !$list = %json_add($list, $var3)
    !endif
    !return $list
!end function

!unquoted function cv($var) /'для компактности вывода функция названа cv - checkVariable()'/
    !if $var != ""
    !$result = $var
    !endif
    !return $result
!end function

!unquoted function cve($var) /'для компактности вывода функция названа cve - checkVariableExist()'/
    !$result = ""
    !if %variable_exists($var)
        !$result = $var
    !endif
    !return $result
!end function

!unquoted procedure printRaw($var1, $var2="", $var3="", $var4="", $var5="", $var6="", $var7="", $var8="", $var9="", $var10="")
cv($var1) cv($var2) cv($var3) cv($var4) cv($var5) cv($var6) cv($var7) cv($var8) cv($var9) cv($var10)
!endprocedure



printParties("participant", "Тестовый участник\\n007", agent)



@enduml