@startuml
/'TODO Нужна процедура для стратегии вывода текста в оригинальном синтаксисе планта по стратегии в json'/

a->b: "Hello world"

!$originalSyntaxMap = {
    "party": {
        "list": ["type", "name", "alias", "orderValue"],
        "type": "",
        "name": "",
        "as": "as",
        "alias": "",
        "order": "order",
        "orderValue": ""
    }
}


!unquoted function createJsonObject($names, $values)
    !if %get_json_type($names) != "array" || %get_json_type($names) != "object"
        !$names = %splitstr($names, ",")
    !endif
    !if %get_json_type($values) != "array" || %get_json_type($values) != "object"
        !$values = %splitstr($values, ",")
    !endif
    !$i = 0
    !$tempObject = {}
    !foreach $item in $values
        !$tempObject = %json_add($tempObject, $names[$i], $values[$i])
        !$i = $i + 1
    !endfor
    !return $tempObject
!end function

!unquoted procedure setOriginObject($path, $type, $values)
    !$tempList = $path[$type].list
    !$objectToAdd = createJsonObject($tempList, $values)
!endprocedure

!unquoted procedure output($list1, $list2)
    !$list1 = %string($list1)
    !$list2 = %string($list2)
    !$out = %call_user_func("createJsonObject", $list1, $list2)
    note across: %get_json_type($out):\n$out
!endprocedure

!unquoted procedure testAddToList($var1, $var2, $var3)
    !global $list = []
    !$list = %json_add($list, $var1)
    !$list = %json_add($list, $var2)
    !$list = %json_add($list, $var3)
    note across: $list\n %get_json_type($list)
!endprocedure

testAddToList("cube", "blackbig", "")
output("type,color", $list)

@enduml