@startuml
/'Вспомогательная процедура отрисовки участников: формирует мапу имя:алиас'/
!unquoted procedure parties($partyType, $name="", $alias="", $order="")
%invoke_procedure("checkPartyInput", $partyType, $name, $alias, $order)
!endprocedure

!unquoted procedure checkParties($parties)
    !$parties = %splitstr($parties, ",")
    !foreach $item in $parties
        !if %not(%json_key_exists($currentAliasMap, $item))
            %invoke_procedure("checkPartyInput", $item)
        !endif
    !endfor
!endprocedure

!unquoted procedure checkPartyInput($partyType, $name="", $alias="", $order="")
    /'Вместо дефолтного типа участников можно передать несколько алиасов'/
    !if %not(%json_key_exists($defaultPartyTypes, $partyType))
        !$alias = $partyType
        !$partyType = ""
        !$name = ""
        !$order = ""
    /'Если не передан дефолтный тип участника, можно указать только 1 алиас'/
    !elseif %size(%splitstr($alias, ",")) > 1
        %invoke_procedure("serviceError", parties, "добавление участника\nс более чем одним алиасом", $alias)
    !endif
    /'Переходим к подготовке объекта для добавления в диаграмму'/
    %invoke_procedure("buildAliasToAdd", $partyType, $name, $alias, $order)
!endprocedure

!unquoted procedure buildAliasToAdd($type="", $name="", $alias="", $order="")
    !$alias = %splitstr($alias, ",")
    !$defaultAttr = ["alias", "type", "name", "order"]
    !foreach $item in $alias
        !$partyAttributes = {}
        /'Формируем объект для добавления в текущий список участников'/
        !foreach $attr in $defaultAttr
            !$value = %get_variable_value("$"+$attr)
            !if $attr == "alias"
                !$value = $item
            !endif
            !$partyAttributes = %json_add($partyAttributes, $attr, $value)
        !endfor
        %invoke_procedure("checkAliasAttributes", $item, $partyAttributes)
    !endfor
!endprocedure

!unquoted procedure checkAliasAttributes($alias, $partyAttributes)
        /'Проверка orderId'/
        !if $partyAttributes.order == ""
            /'TODO продумать, точно ли здесь нужно orderId считать, что в боксах будет'/
            !$orderId = $orderId + 1
            !$partyAttributes = %json_set($partyAttributes, order, $orderId)
        !endif
        /'Если alias найден в текущей диаграмме $currentAliasMap'/
        !if %json_key_exists($currentAliasMap, $alias)
            %invoke_procedure("serviceError", parties, "добавление участника\nс уже используемым алиасом", $alias)
        !endif
        !foreach $field in ["type", "name"]
            !$value = ""
            !if %json_key_exists($customAliasMap, $alias)
                /'Если alias найден в пользовательских настройках'/
                !if $partyAttributes[$field] == ""
                    !$value = $customAliasMap[$alias][$field]
                /'Если alias найден в пользовательских настройках, но объявлен, как новый участник'/
                !elseif $partyAttributes[$field] != "" /'&& $partyAttributes[$field] != $customAliasMap[$alias][$field]'/
                    %invoke_procedure("todo","Проверьте customAliasMap, возможно стоит актуализировать пользовательские настройки.")
                !endif
            !else
                /'Если alias нигде не найден - новый участник'/
                !$functionName = "get" + %call_user_func("getNameByAlias", $field) + "ByAlias"
                !if $partyAttributes[$field] == ""
                    !$value = %call_user_func($functionName, $alias)
                !endif
                !$todoText = "Добавьте в customAliasMap нового участника " + $alias + ": " + $partyAttributes
                %invoke_procedure("todo",$todoText)
            !endif
            !if $value != ""
                !$partyAttributes = %json_set($partyAttributes, $field, $value)
            !endif
        !endfor
        !$currentAliasMap = %json_add($currentAliasMap, $alias, $partyAttributes)
        %invoke_procedure("outputAliasController", $alias)
!endprocedure

!unquoted function getNameByAlias($var)
    !$nameByAlias = %upper(%substr($var,0,1)) + %substr($var,1)
    !return $nameByAlias
!end function

!unquoted function getTypeByAlias($var)
    !$typeByAlias = "participant"
    !foreach $item in %get_json_keys($partyTypesDictionary)
        !if %strpos($var, $item) >= 0
            !$typeByAlias = $partyTypesDictionary[$item]
            !break
        !endif
    !endfor
    !return $typeByAlias
!end function


!unquoted procedure outputAliasController($alias)
$currentAliasMap[$alias].type "$currentAliasMap[$alias].name" as $currentAliasMap[$alias].alias order $currentAliasMap[$alias].order
!endprocedure

/'Процедура объединения участников в боксы'/
!unquoted procedure BOX($name, $color, $parties)
!$partiesToPaint = %splitstr($parties, ",")
!$colorToBuild = colorController($color)
box $name $colorToBuild
    !foreach $item in $partiesToPaint
        !if %json_key_exists($currentAliasMap, $item)
            !$temp = {}
            !$temp = %json_merge($temp, $currentAliasMap[$item])
            !$orderId = %intval($temp.order) - 1
            !$currentAliasMap = %json_remove($currentAliasMap, $item)
        !endif
        %invoke_procedure("parties", $item)
    !endfor
end box
%invoke_procedure("tagPartiesFromBoxInCurrentAliasMap",$parties)
%invoke_procedure("setOriginalBox", $name, $color, $parties)
!endprocedure

!unquoted procedure tagPartiesFromBoxInCurrentAliasMap($parties)
    !$partiesToPaint = %splitstr($parties, ",")
    !foreach $field in $partiesToPaint
        !$temp = {}
        !$temp = %json_set($temp, $currentAliasMap[$field])
        !$temp = %json_add($temp, box, 1)
        !$currentAliasMap = %json_set($currentAliasMap, $field, $temp)
    !endfor
!endprocedure

/'Сохранение данных для построения диаграммы в оригинальном синтаксисе'/
!unquoted procedure setOriginalBox($name, $color, $parties)
!$temp = {}
!$temp = %json_add($temp, "type", "box")
!$temp = %json_add($temp, "name", $name)
!$temp = %json_add($temp, "color", $color)
!$temp = %json_add($temp, "parties", $parties)
!$originalSyntaxMap = %json_add($originalSyntaxMap, $temp)
!$techId = $techId + 1
!endprocedure