@startuml
/'Вспомогательная процедура отрисовки участников: формирует мапу имя:алиас'/

!unquoted procedure parties($partyType, $name="", $alias="", $order="")
%invoke_procedure("checkPartyInput", $partyType, $name, $alias, $order)
!endprocedure

!unquoted procedure checkPartyInput($partyType, $name="", $alias="", $order="")
    /'Вместо дефолтного типа участников можно передать несколько алиасов'/
    !if %not(%json_key_exists($defaultPartyTypes, $partyType))
        !$alias = $partyType
        !$partyType = ""
        !$name = ""
        !$order = ""

    /'Если не передан дефолтный тип участника, можно указать только 1 алиас'/
    !elseif %size(%splitstr($alias, ",")) > 1
        %invoke_procedure("serviceError", parties, "добавление участника\nс более чем одним алиасом", $alias)
    !endif

    /'Переходим к подготовке объекта для добавления в диаграмму'/
    %invoke_procedure("buildAliasToAdd", $partyType, $name, $alias, $order)
!endprocedure

!unquoted procedure buildAliasToAdd($type="", $name="", $alias="", $order="")
    !$alias = %splitstr($alias, ",")
    !$defaultAttr = ["alias", "type", "name", "order"]
    !foreach $item in $alias
        !$partyAttributes = {}
        /'Формируем объект для добавления в текущий список участников'/
        !foreach $attr in $defaultAttr
            !$value = %get_variable_value("$"+$attr)
            !if $attr == "alias"
                !$value = $item
            !endif
            !$partyAttributes = %json_add($partyAttributes, $attr, $value)
        !endfor
        %invoke_procedure("checkAliasAttributes", $item, $partyAttributes)
    !endfor
!endprocedure

!unquoted procedure checkAliasAttributes($alias, $partyAttributes)
        /'Проверка orderId'/
        !if $partyAttributes.order == ""
            /'TODO продумать, точно ли здесь нужно orderId считать, что в боксах будет'/
            !$orderId = $orderId + 1
            !$partyAttributes = %json_set($partyAttributes, order, $orderId)
        !endif

        /'Если alias найден в текущей диаграмме $currentAliasMap'/
        !if %json_key_exists($currentAliasMap, $alias)
            %invoke_procedure("serviceError", parties, "добавление участника\nс уже используемым алиасом", $alias)
        !endif

        /'Если alias найден в кастомных настройках $customAliasMap'/
        !if %json_key_exists($customAliasMap, $alias)

            !if $partyAttributes.type == ""
                !$partyAttributes = %json_set($partyAttributes, type, $customAliasMap[$alias].type)
            !endif

            !if $partyAttributes.name == ""
                !$partyAttributes = %json_set($partyAttributes, name, $customAliasMap[$alias].name)
            !endif
        !endif

        /'Если alias нигде не найден - новый участник'/
        !if %not(%json_key_exists($customAliasMap, $alias))
            !if $partyAttributes.name == ""
                !$partyAttributes = %json_set($partyAttributes, name, %call_user_func("getNameByAlias", $alias))
            !endif
            !if $partyAttributes.type == ""
                !$partyAttributes = %json_set($partyAttributes, type, %call_user_func("getTypeByAlias", $alias))
            !endif
            %invoke_procedure("todo","Добавляется интеграция с новым участником: $partyAttributes.name")
        !endif
        !$currentAliasMap = %json_add($currentAliasMap, $alias, $partyAttributes)
        %invoke_procedure("outputAliasController", $partyAttributes)
!endprocedure

!unquoted function getNameByAlias($var)
    !$nameByAlias = %upper(%substr($var,0,1)) + %substr($var,1)
    !return $nameByAlias
!end function

!unquoted function getTypeByAlias($var)
    !$typeByAlias = "participant"
    !foreach $item in %get_json_keys($partyTypesDictionary)
        !if %strpos($var, $item) > 0 || %strpos($var, $item) == 0
            !$typeByAlias = $partyTypesDictionary[$item]
        !endif
    !endfor
    !return $typeByAlias
!end function

!unquoted procedure outputAliasController($partyAttributes)
$partyAttributes.type "$partyAttributes.name" as $partyAttributes.alias order $partyAttributes.order
!endprocedure

/'TODO Дописать боксы'/