@startuml
/'Цель этой диаграммы: показать зависимость разработчика от требований и разработку требований от разработчика.
Текущая итерация работает, но все ли она покрывает?
если придет имя, которого нет в базе
если придем сумма, больше чем остаток по счтеу (обработка ошибок)
если будет много счетов
если появятся новые операции - например попросить в долг
если появятся отложенные операции (ассинхрон)
если у нас есть прямй досутп к бд, как защитить? возьму и поставлю себе 10000000
'/


title Постановка и реализация в коде на примере оплаты

== Реализация в постановке ==
skinparam maxmessageSize 150

actor "Alice" as alice
participant "PaymentService" as srv
database "BackOffice" as bo
actor "Bob" as bob

alice ->o srv++: Перевести деньги Бобу

srv -> bo++: Запросить отстатки на счете Alice и Bob
bo --> srv--: Остатки по счетам

srv -> srv: Проверить остатки

break У Алисы не хватает денег на перевод
    srv --> alice: Денег не хватает
end

srv -> bo++: Сформировтаь транзакции: пополнить счет Боба, уменьшить счет Алисы
bo --> srv--: Остатки по счетам изменены
srv ->> bob: Ваш счет пополнен
srv --> alice --: Операция выполнена

== Реализация в коде ==

/'env'/
!$id = 0

!$db = {
    "alice" : [1000,0,500],
    "bob" : [50]
}

!$defOperationResult = ["Ошибка","Успех"]

/'operation = {
from
to
amount
}
'/

!unquoted function compare($a, $b)
    /'По дефолту считаем, что $a <= $b'/
    !$i = 0
    !if $a > $b
        !$i = 1
    !endif
    !return $i
!end function

!unquoted function getBalance($client)
    !return %intval($db[$client][0])
!end function

!unquoted procedure changeBalance($client,$operation,$amount)
    !if $operation == 0
        !$newBalance = getBalance($client) - $amount
    !else
        !$newBalance = getBalance($client) + $amount
    !endif

    !$value = []
    !$value = %json_add($value, $newBalance)
    !$value = %json_merge($value, $db[$client])
    !$db = %json_set($db, $client, $value)
!end procedure

!unquoted procedure operationController($data)
    srv -> srv: Подготовить данные для сравнения
    !$data = %str2json($data)
    !$amount = %intval($data.amount)
    !$from = $data.from
    !$to = $data.to

    !$operationResult = 0
    srv -> bo++: Запросить остатки по счетам $from и $to
    bo --> srv--: Остатки
    srv -> srv: Сравнить остаток на счете $from с суммой операции $amount
    !if %call_user_func(compare, %call_user_func("getBalance",$from), $amount)
        %invoke_procedure("changeBalance",$from,0,$amount)
        %invoke_procedure("changeBalance",$to,1,$amount)
        srv -> bo++: Изменить остатки по счетам $from и $to
        bo --> srv--: Успех
        /'TODO Написать функцию вывода результата'/
        /'TODO Шаблонизировтаь результат и ошибки'/
        !$operationResult = 1
        note across #lightgreen:**Выполнение программы**\n----\nОперация: перевод от $from к $to на сумму $amount.\nРезультат операции: $defOperationResult[$operationResult]\nСообщение для $from:\nОсуществлен перевод с Вашего счета на счет $to. Ваш баланс: getBalance($from)
        srv -> $to: Ваш счет пополнен
        srv --> $from--: Деньги переведены
    !else
        !$newBalanceFrom = $accBalanceFrom
        !$newBalanceTo = $accBalanceTo
        note across#orange:**Выполнение программы**\n----\nОперация: перевод от $from к $to на сумму $amount.\nРезультат операции: $defOperationResult[$operationResult]\nСообщение для $from:\nНедостаточно средств. Ваш баланс: getBalance($from)
        break Не хватает
        srv --> $from--: Недостаточно средств
        end
    !endif
!end procedure

!unquoted function buildOperation($from, $to, $amount)
    !$operation = {}
    !$operation = %json_add($operation, from, $from)
    !$operation = %json_add($operation, to, $to)
    !$operation = %json_add($operation, amount, $amount)
    !return $operation
!end function

!unquoted procedure main($from, $to, $amount)
    !$id = $id + 1
    == Операция с ид $id ==
    note across:До операции:\n----\n$db
    $from ->o srv++: Перевести $amount баксов $to
    srv -> srv: Сформировать транзакцию
    !$operation = %call_user_func("buildOperation",$from, $to, $amount)
    srv -> srv: Выполнение проверок
    %invoke_procedure(operationController, $operation)
    note across:После операции:\n----\n$db
!endprocedure

main(alice,bob,25)
main(bob,alice,350)
main(alice,bob,0)
main(alice,bob,-1)
@enduml