@startuml
/'Нужно зависимость от if победить за счет полиморфизма'/
participant "Входящая операция" as op
participant "Счет" as acc
op -> acc: Пришла операция

/'Нужно докрутить этот пример до операции со счетом, чтобы показать на диаграмме полиморфизм, инкапсуляцию и наследование'/

/'env'/
!$defCommand = ["plus","minus"]

!unquoted function plus($a, $b)
    !return $a + $b
!end function

!unquoted function minus($a, $b)
    !return $a - $b
!end function

!unquoted function comparer($a, $b)
    !if $a < $b
        !$i = 0
    !else
        !$i = 1
    !endif
    !return $i
!end function

!unquoted procedure commandController($a, $b)
    !$a = %intval($a)
    !$b = %intval($b)
    !$i = %call_user_func(comparer, $a, $b)
    !$result = %call_user_func($defCommand[$i], $a, $b)
    note across: На входе: $a и $b\nВыбранная команда: $defCommand[$i]\nИтог вычислений: $result
!end procedure

!unquoted procedure main($a,$b)
    %invoke_procedure(commandController, $a, $b)
!endprocedure

main(50,100)

@enduml