@startuml
!include C:\Users\valik\IdeaProjects\PlantUML_SequenceLib\SequenceLib\src\SequenceLibIncludeFile_v5.puml

a->b: Тестируем алиасы

!$currentAliasMap = {
    "user" : {
      "type": "actor",
      "name": "Пользователь"
    }}
parties("user1,queue","",,)
note across:%string(%upper(%substr(alias,0,1)) + %substr(alias,1))
@enduml