@startuml
!unquoted procedure enterWebSite($nameSite)
    !$siteAttr = %call_user_func(webSiteLogic, $nameSite)
    participant "$siteAttr.name" as $nameSite order 1
    user -> $nameSite ++: Войти через testId
    $nameSite -> testid ++: Поднять фронт TEST ID,\nпередав параметры:\nname = $nameSite, clientId = $siteAttr.clientId, scope = $siteAttr.scope
!endprocedure

!unquoted function webSiteLogic($var)
    %invoke_procedure("log",webSiteLogic, start, $var)
    !if %json_key_exists($siteAttributes, $var)
        !$site = $siteAttributes[$var]
    !else
        !$site = {}
        !$site = %json_add($site, "name", $var)
        !$site = %json_add($site, "alias", $var)
    !endif
    %invoke_procedure("log",webSiteLogic, finish, $site)
    !return $site
!end function