@startuml
!$customAliasMap = {
    "user" : {
      "type": "actor",
      "name": "Пользователь"
    },
    "srv" : {
      "type": "participant",
      "name": "Ваш сервис"
    },
    "core": {
      "type": "participant",
      "name": "Ядро"
    }
}