@startuml
'!include C:\Users\valik\IdeaProjects\PlantUML_SequenceLib\SequenceLib\src\enviroment\ParametersAndSwitchers.puml

!include customAliasMap.puml
!include customAuditMap.puml
!include customConfigMap.puml
!include customMetricMap.puml
!include customErrorMap.puml
!include partyTypes.puml