@startuml
'!include C:\Users\valik\IdeaProjects\PlantUML_SequenceLib\SequenceLib\src\enviroment\ParametersAndSwitchers.puml

/'Разделение логики между версиями'/
!if %variable_exists("$majorVersion")
    !include major5/customAliasMap.puml
    !include major5/customAuditMap.puml
    !include major5/customConfigMap.puml
    !include major5/customMetricMap.puml
    !include major5/customErrorMap.puml
    !include major5/partyTypes.puml
!else
    !include oldVersion/customAliasMap.puml
    !include oldVersion/customAuditMap.puml
    !include oldVersion/customConfigMap.puml
    !include oldVersion/customMetricMap.puml
    !include oldVersion/customErrorMap.puml
    !include oldVersion/partyTypes.puml
!endif
