@startuml
/'Мапа алиасов'/
!$defaultAliasTypes = {
    "user": "actor",
    "client": "actor",
    "redis": "database",
    "PostgreSql": "database",
    "postgre": "database",
    "postgres": "database",
    "postgreSQL": "database",
    "kafka": "queue",
    "queue": "queue",
    "rabbit": "queue",
    "rabbitMQ": "queue",
    "MQ": "queue"
   }

!$defaultPartyTypes = {
    "participant": "Участник",
    "actor": "Пользователь",
    "database": "БД",
    "queue": "Очередь",
    "boundary": "Граница",
    "control": "Контроль",
    "entity": "Сущность",
    "collections": "Коллекция"
}